### ISSUE TITLE
whamm panics when multiple actions matched at the same probe

### ISSUE THREAD

**Issue by wavid-b** [ejrgilbert/whamm#106]
Occurs when you have duplicate probing events
For example:
```DTrace
i32 count;
wasm:opcode:call:before {
    count++;
}
wasm:opcode:call:before {
    count++;
}

```
will cause

BACKTRACE:
``` --> wasm_playground/maps/src/add_map.mm

thread 'main' panicked at src/common/error.rs:76:9:
Fatal: Reached a fatal error or warning. Exiting...
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: whamm::common::error::ErrorGen::fatal_report
             at ./src/common/error.rs:76:9
   3: whamm::common::error::ErrorGen::add_error
             at ./src/common/error.rs:44:13
   4: whamm::common::error::ErrorGen::unexpected_error
             at ./src/common/error.rs:339:9
   5: whamm::verifier::verifier::check_duplicate_id
             at ./src/verifier/verifier.rs:46:21
   6: whamm::verifier::builder_visitor::SymbolTableBuilder::add_probe
             at ./src/verifier/builder_visitor.rs:207:12
   7: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_probe
             at ./src/verifier/builder_visitor.rs:617:9
   8: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_event::{{closure}}::{{closure}}
             at ./src/verifier/builder_visitor.rs:603:17
   9: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/iter/macros.rs:254:21
  10: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_event::{{closure}}
             at ./src/verifier/builder_visitor.rs:602:13
  11: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:855:29
  12: core::iter::traits::iterator::Iterator::fold
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2640:21
  13: core::iter::traits::iterator::Iterator::for_each
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:858:9
  14: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_event
             at ./src/verifier/builder_visitor.rs:601:9
  15: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_package::{{closure}}
             at ./src/verifier/builder_visitor.rs:581:31
  16: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:855:29
  17: core::iter::traits::iterator::Iterator::fold
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2640:21
  18: core::iter::traits::iterator::Iterator::for_each
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:858:9
  19: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_package
             at ./src/verifier/builder_visitor.rs:579:9
  20: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_provider::{{closure}}
             at ./src/verifier/builder_visitor.rs:561:33
  21: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:855:29
  22: core::iter::traits::iterator::Iterator::fold
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2640:21
  23: core::iter::traits::iterator::Iterator::for_each
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:858:9
  24: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_provider
             at ./src/verifier/builder_visitor.rs:559:9
  25: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_script::{{closure}}
             at ./src/verifier/builder_visitor.rs:541:43
  26: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:855:29
  27: core::iter::traits::iterator::Iterator::fold
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:2640:21
  28: core::iter::traits::iterator::Iterator::for_each
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/iterator.rs:858:9
  29: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_script
             at ./src/verifier/builder_visitor.rs:538:9
  30: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_whamm::{{closure}}
             at ./src/verifier/builder_visitor.rs:469:32
  31: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/iter/macros.rs:254:21
  32: <whamm::verifier::builder_visitor::SymbolTableBuilder as whamm::parser::types::WhammVisitorMut<()>>::visit_whamm
             at ./src/verifier/builder_visitor.rs:466:9
  33: whamm::verifier::verifier::build_symbol_table
             at ./src/verifier/verifier.rs:27:5
  34: whamm::get_symbol_table
             at ./src/main.rs:185:18
  35: whamm::run_instr
             at ./src/main.rs:104:28
  36: whamm::try_main
             at ./src/main.rs:64:13
  37: whamm::main
             at ./src/main.rs:39:21
  38: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by wavid-b** [comment]
Same error even if the predicates are different - this might just be the multiple probe bug

**Comment by wavid-b** [comment]
Error is in Builder visitor:
``` 
fn add_probe(&mut self, probe: &dyn Probe) {
        /*check_duplicate_id is necessary to make sure we don't try to have 2 records with the same string pointing to them in the hashmap.
        In some cases, it gives a non-fatal error, but in others, it is fatal. Thats why if it finds any error, we return here ->
        just in case it is non-fatal to avoid having 2 strings w/same name in record */
        if check_duplicate_id(&probe.mode_name(), &None, true, &self.table, self.err) {
            return;
        } ...
```
Solution may be to add an ID to the end of each probe so that it isn't identified by its makeup alone. Issue with that is it has to be in the AST as well.

**Comment by wavid-b** [comment]
The concept of probe numbering generated in the simple AST can be used to fix this bug -- append the number to the string for each probe before adding it to the ST. You would have to change when the "numbering" itself happens
